CinemaApplication/Controllers/MoviesController.cs
using CinemaApplication.Areas.Admin.Services;
using CinemaApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaApplication.Controllers
{ 
   
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;

        public MoviesController(IMoviesService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Filter(string searchString)
        {
            var allMovies = await _service.GetAllAsync(n => n.MovieCategory);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allMovies.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.MovieCategory.Name.ToLower().Contains(searchString.ToLower())).ToList();

                var filteredResultNew = allMovies.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResult);
            }

            return View("Index", allMovies);
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var allMovies = await _service.GetAllAsync(n=>n.MovieCategory);

            return View(allMovies);
        }
        public async Task<IActionResult> Details(int id)
        {
            var movieDetail = await _service.GetMovieByIdAsync(id);
            if (movieDetail == null) return View("NotFound");

            return View(movieDetail);
        }


    }

}

CinemaApplication/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CinemaApplication.Data;
using CinemaApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaApplication.Controllers
{
    public class PagesController : Controller
    {
        private readonly ApplicationDbContext context;

        public PagesController(ApplicationDbContext context)
        {
            this.context = context;
        }

        // GET / or /slug
        public async Task<IActionResult> Page(string slug)
        {
            if (slug == null)
            {
                return View(await context.Pages.Where(x => x.Slug == "home").FirstOrDefaultAsync());
            }

            Page page = await context.Pages.Where(x => x.Slug == slug).FirstOrDefaultAsync();

            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }
    }
}

CinemaApplication/Areas/Admin/Views/Shared/NotFound.cshtml
<div class="row" style="margin-top:100px">
    <div class="col-md-6 offset-3 text-center" style="background-color:darkred;color:white;">
        <h1  >Not Found</h1>
        <hr />
        <a style="background-color:darkred;color:white;" class="btn" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>

CinemaApplication/Areas/Admin/Views/Shared/_CreateItem.cshtml
@model string;


    <div style="right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>

CinemaApplication/Areas/Admin/Views/Shared/_Identity.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<ApplicationUser> UserManager

@if (!User.Identity.IsAuthenticated)
{
<a style="background-color:darkred" class="btn btn-outline white my-2 my-sm-0" asp-controller="Account" asp-action="Login">
    <i class="bi bi-box-arrow-in-right"></i> Log in
</a>
                <span style="padding: 5px;"></span>

                                <a style="background-color:darkred" class="btn btn-outline white my-2 my-sm-0" asp-controller="Account" asp-action="Register">
                                    <i class="bi bi-person-plus"></i> Register
                                </a> }
                            else
                            { @*User profile section*@
                                            <a style="background-color:darkred;margin-right:10px;color:white" class="btn btn-outline white my-2 my-sm-0" asp-area="Admin"  asp-controller="Account" asp-action="Register" >
                                                <i class="bi bi-person-plus"></i> Create Admin
                                            </a>
                                                            <div class="dropdown">
                                                                <button style="background-color:darkred;color:white" class="btn btn-outline white dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                                                                        aria-expanded="false">
                                                                    <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
                                                                </button>
                                                                <ul class="dropdown-menu" aria-labelledby="profile-btn">
                                                                    <li>
                                                                        <a  style="color:darkred"; class="dropdown-item" asp-controller="Orders" asp-action="Index">
                                                                            <i  style="color:darkred;" class="bi bi-list"></i> Orders
                                                                        </a>
                                                                    </li>

                                                                    @if (User.IsInRole("Admin") || User.IsInRole("Super"))
                                                                    {
                                                    <li>
                                                        <a style="color:darkred"; class="dropdown-item" asp-controller="Account" asp-action="Users">
                                                            <i style="color:darkred;"  class="bi bi-people"></i> Users
                                                        </a>
                                                    </li>}
                                                                </ul>
                                                            </div>
                                                                            <span style="padding: 5px;"></span>
                                                                                            <form asp-controller="Account" asp-action="Logout">
                                                                                                <button class="btn btn-outline-danger my-2 my-sm-0">
                                                                                                    <i class="bi bi-box-arrow-in-right"></i> Log out
                                                                                                </button>
                                                                                            </form>}

CinemaApplication/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ELI-Cinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <script src="https://kit.fontawesome.com/e4ecf4b178.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4-4.1.1/jq-3.3.1/dt-1.10.23/b-1.6.5/fc-3.3.2/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.1/datatables.min.css" />
    <style>
        .nav-item a, dropdown a,dropsown i{
            color:darkred;
        }
        
    </style>
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index"><i style="color:darkred;" class='fas fa-home fa-fw fa-x'></i></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @*<ul >
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bi bi-gear"></i> Management
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" asp-area="Admin" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                    <a class="dropdown-item" asp-area="Admin" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                    <a class="dropdown-item" asp-area="Admin" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                    <a class="dropdown-item" asp-area="Admin" asp-controller="Categories" asp-action="Index"><i class="bi bi-person-square"></i> Genres</a>
                </div>
            </li>*@
                    @*<li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>

            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Pages" asp-action="Index">Pages</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Categories" asp-action="Index">Genres</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Movies" asp-action="Index">Movies</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Actors" asp-action="Index">Actors</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Cinemas" asp-action="Index">Cinemas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Producers" asp-action="Index">Producers</a>
            </li>*@

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index"><i class="bi bi-film"></i> Movies</a>*@
                            <a class="navbar-brand" asp-area="Admin" asp-controller="Movies" asp-action="Index"><i style="color:darkred" class='fas fa-film fa-spin fa-x'>ELI</i></a>

                        </li>


                        <li class="nav-item dropdown">
                            <a style="color:darkred" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i style="color:darkred" class="  bi bi-gear"></i> Management
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Movies" asp-action="Index"><i style="color:darkred" class="fas fa-film"></i> Movies</a>

                                <a class="dropdown-item" asp-area="Admin" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Categories" asp-action="Index"><i class="fas fa-theater-masks"></i> Genres</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Pages" asp-action="Index"><i class="fa fa-file" aria-hidden="true"></i> Pages</a>
                            </div>
                        </li>

                    </ul>


                </div>
                <partial name="_Identity.cshtml" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />

            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CinemaApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    
  
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>


    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4-4.1.1/jq-3.3.1/dt-1.10.23/b-1.6.5/fc-3.3.2/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.1/datatables.min.js"></script>



    @RenderSection("Scripts", required: false)
</body>
</html>

CinemaApplication/Areas/Admin/Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success notification">
        @TempData["Success"]
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["Error"]
    </div>
}
@if (TempData["Info"] != null)
{
    <div class="alert alert-info notification">
        @TempData["Info"]
    </div>
}