CinemaApplication/Models/Cinema.cs
using CinemaApplication.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaApplication.Models
{
    public class Cinema: IEntityBase
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Cinema Logo")]
        [Required(ErrorMessage = "Cinema logo is required")]
        public string Logo { get; set; }

        [Display(Name = "Cinema Name")]
        [Required(ErrorMessage = "Cinema name is required")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        [Required(ErrorMessage = "Cinema description is required")]
        public string Description { get; set; }

        //Relationships
        public List<Movie> Movies { get; set; }
    }
}

CinemaApplication/Areas/Admin/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using CinemaApplication.Models;
using CinemaApplication.Areas.Admin.Services;
using CinemaApplication.Data.Static;
using CinemaApplication.Data;
using Microsoft.EntityFrameworkCore;

namespace CinemaApplication.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = UserRoles.Both)]

    public class CinemasController : Controller
    {
        private readonly ICinemasService service;
        private readonly ApplicationDbContext context;


        public CinemasController(ICinemasService service, ApplicationDbContext context)
        {
            this.service = service;
            this.context = context;
        }

        
        public async Task<IActionResult> Index()
        {
           
            var data = await service.GetAllAsync();
            return View(data);
        }


        //Get: Cinemas/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid) return View(cinema);
            await service.AddAsync(cinema);
            TempData["Success"] = "The Cinema was added!";

            return RedirectToAction(nameof(Index));
        }

        //Get: Cinemas/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var cinemaDetails = await service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }

        //Get: Cinemas/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var cinemaDetails = await service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid) return View(cinema);
            await service.UpdateAsync(id, cinema);
            return RedirectToAction(nameof(Index));
        }

        ////Get: Cinemas/Delete/1
        //public async Task<IActionResult> Delete(int id)
        //{
        //    var cinemaDetails = await service.GetByIdAsync(id);
        //    if (cinemaDetails == null) return View("NotFound");
        //    return View(cinemaDetails);
        //}

        //[HttpPost, ActionName("Delete")]
        //public async Task<IActionResult> DeleteConfirm(int id)
        //{
        //    var cinemaDetails = await service.GetByIdAsync(id);
        //    if (cinemaDetails == null) return View("NotFound");

        //    await service.DeleteAsync(id);
        //    return RedirectToAction(nameof(Index));
        //}
        public async Task<IActionResult> Delete(int id)
        {
            Cinema pro = await context.Cinemas.FindAsync(id);
            var movie = await context.Movies.Where(n => n.CinemaId == id).ToListAsync();

            if (pro == null)
            {
                TempData["Error"] = "The Cinema does not exist!";
            }
            else if (movie.Count != 0)
            {
                TempData["Error"] = "Can not delete this cinema, cause there are movies in this cinema!";
            }
            else
            {
                context.Cinemas.Remove(pro);
                await context.SaveChangesAsync();

                TempData["Success"] = "The cinema has been deleted!";
            }

            return RedirectToAction("Index");
        }
    }
}

CinemaApplication/Areas/Admin/Views/Cinemas/Create.cshtml
@model Cinema

@{
    ViewData["Title"] = "Add a new cinema";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New Cinema</h1> 
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="CinemaLogoPreview" class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Logo" class="control-label"></label>
                        <input asp-for="Logo" class="form-control" />
                        <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create"class=" btn  darkred  float-right" style="background-color:darkred;color:white"/>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('CinemaLogoPreview');
            output.src = $("#Logo").val();
        })
        $("#Logo").on("change", function () {
            var output = document.getElementById('CinemaLogoPreview');
            output.src = $(this).val();
        })
    </script>
}

CinemaApplication/Areas/Admin/Views/Cinemas/Delete.cshtml
@model Cinema

@{
    ViewData["Title"] = "Delete cinema";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete confirmation for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="max-width: 150px" id="LogoPreview" />
                </div>
                <div class="form-group">
                    <label asp-for="Logo" class="control-label"></label>
                    <input asp-for="Logo" class="form-control" readonly />
                    <span asp-validation-for="Logo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" readonly />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" readonly />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                    </form>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('LogoPreview');
            output.src = $("#Logo").val();
        })
    </script>
}

CinemaApplication/Areas/Admin/Views/Cinemas/Details.cshtml
@model Cinema

@{
    ViewData["Title"] = "Details of the cinema";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="max-width: 150px" id="LogoPreview" />
                </div>
                <div class="form-group">
                    <label asp-for="Logo" class="control-label"></label>
                    <input asp-for="Logo" class="form-control" readonly />
                    <span asp-validation-for="Logo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" readonly />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" readonly />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                   
                        <a class=" btn  darkred  float-right" style="background-color:darkred;color:white" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                    
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('LogoPreview');
            output.src = $("#Logo").val();
        })
    </script>
}

CinemaApplication/Areas/Admin/Views/Cinemas/Edit.cshtml
@model Cinema

@{
    ViewData["Title"] = "Update cinema";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update cinema</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="CinemaLogoPreview" class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Logo" class="control-label"></label>
                        <input asp-for="Logo" class="form-control" />
                        <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class=" btn  darkred  float-right" style="background-color:darkred;color:white" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('CinemaLogoPreview');
            output.src = $("#Logo").val();
        })
        $("#Logo").on("change", function () {
            var output = document.getElementById('CinemaLogoPreview');
            output.src = $(this).val();
        })
    </script>
}

CinemaApplication/Areas/Admin/Views/Cinemas/Index.cshtml
@model IEnumerable<Cinema>

@{
    ViewData["Title"] = "List of Cinemas";
}
<em><h3>Cinemas</h3></em>
<a asp-action="Create">
    <i class="bi bi-plus-circle"></i> Add New
</a>
<hr />
@*<div class="row">
        <div class="col-md-8 offset-md-2">

            <table id="myActorTable" class="table table-hover table-sm">
                <thead>
                    <tr class="text-center">
                        <th>@Html.DisplayNameFor(model => model.Logo)</th>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th>@Html.DisplayNameFor(model => model.Description)</th>

                        <th>Actions</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td >
                                <img class="rounded-circle" src="@item.Logo" alt="@item.Name" style="max-width: 100px" />
                            </td>
                            <td >
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td >
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>

                            <td  style="max-width:fit-content">
                                <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a>|
                                <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a>|
                                <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                            </td>

                        </tr>
                    }
                </tbody>

            </table>
            <div style="position:fixed; right:25px; bottom:25px;" class="text-white">
                <a asp-controller="Cinemas" asp-action="Create" class="btn badge-success">Add New</a>
            </div>

        </div>
    </div>*@
<table id="myTable" class="table table-hover  table-striped table-sm " >
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Image
            </th>
            <th>
                Name
            </th>
            <th data-orderable="false"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="id_@item.Id">
                <td>
                    @item.Id
                </td>
                <td>
                    <img src="@item.Logo" alt="@item.Name" style="max-width: 100px;height:100px;" />
                </td>
                <td>
                    @item.Name
                </td>
                <td style="max-width:fit-content">
                    <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                    <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                    <a class="btn btn-danger text-white " asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                </td>

            </tr>
        }
    </tbody>
</table>


@*@await Html.PartialAsync("_CreateItem", "Cinemas")*@
<br />
<br />