CinemaApplication/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaApplication.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }
        public string Email { get; set; }
        public string UserId { get; set; }
        [ForeignKey(nameof(UserId))]
      
        public ApplicationUser  User { get; set; }

        public List<OrderItem> OrderItems { get; set; }
    }
}

CinemaApplication/Areas/Admin/Controllers/OrdersController.cs
using CinemaApplication.Areas.Admin.Services;
using CinemaApplication.Cart;
using CinemaApplication.Data.Static;
using CinemaApplication.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CinemaApplication.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = UserRoles.Both)]

    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
          
           
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

        public async Task<IActionResult> Delete(int id)
        {
          

            var order = await _ordersService.GetOrderByIdAsync(id);
            if (order == null) return View("NotFound");

            if (order == null)
            {
                TempData["Error"] = "The order does not exist!";
            }
          
            else
            {
                await _ordersService.DeleteAsync(id);

                

                TempData["Success"] = "The order has been deleted!";
            }

            return RedirectToAction("Index");
        }

    }
}

CinemaApplication/Controllers/MoviesController.cs
using CinemaApplication.Areas.Admin.Services;
using CinemaApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaApplication.Controllers
{ 
   
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;

        public MoviesController(IMoviesService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Filter(string searchString)
        {
            var allMovies = await _service.GetAllAsync(n => n.MovieCategory);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allMovies.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.MovieCategory.Name.ToLower().Contains(searchString.ToLower())).ToList();

                var filteredResultNew = allMovies.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResult);
            }

            return View("Index", allMovies);
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var allMovies = await _service.GetAllAsync(n=>n.MovieCategory);

            return View(allMovies);
        }
        public async Task<IActionResult> Details(int id)
        {
            var movieDetail = await _service.GetMovieByIdAsync(id);
            if (movieDetail == null) return View("NotFound");

            return View(movieDetail);
        }


    }

}

CinemaApplication/Controllers/OrdersController.cs
using CinemaApplication.Areas.Admin.Services;
using CinemaApplication.Cart;
using CinemaApplication.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CinemaApplication.Area.Admin.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
          

            return View("OrderCompleted");
        }
    }
}

CinemaApplication/Views/Orders/Index.cshtml
@model List<Order>

@{
    ViewData["Title"] = "All orders";
}


        <p>
            <h4>List of all your orders</h4>
        </p>

        <table id="myTable" class="table table-striped table-hover table-sm">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Movies</th>
                    <th>Total</th>
                  


                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model)
                {
                <tr>
                    <td class="align-middle">@order.Id</td>
                    <td class="align-middle">
                        <ul style="list-style-type:none">
                            @foreach (var item in order.OrderItems)
                            {

                                <img src="@item.Movie.ImageURL" width="100" alt="" />
                                <br />
                                <li>
                                    <div class="" role="alert">
                                        <span class="badge badge-pill badge-light">@item.Amount</span> [@item.Price.ToString("c")] - @item.Movie.Name
                                    </div>
                                </li>

                            }
                        </ul>
                    </td>
                    <td class="align-middle">
                        @order.OrderItems.Select(m => m.Movie.Price * m.Amount).Sum().ToString("c")
                    </td>
                  
                </tr>

                }
            </tbody>
        </table>

CinemaApplication/Views/Orders/OrderCompleted.cshtml
<div style="margin-top:100px;" >
    <div class="col-md-6 offset-3 alert alert-info text-center "  style="background-color:darkred;color:white;">
        <h2>Order completed successfully</h2>
        <p>You can check all your orders in the Orders section of your profile</p>
        <hr />
        <p>Thank you!</p>
    </div>
</div> 

CinemaApplication/Views/Orders/ShoppingCart.cshtml
@using CinemaApplication.ViewModels;
@model ShoppingCartVM

@{
    ViewData["Title"] = " Shopping Cart Summary";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="text-center">
            <h2>Your shopping car summary</h2>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Selected Amount</th>
                    <th>Movie</th>
                    <th>Price</th>
                    <th>Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
                {
                    <tr>
                        <td class="align-middle">@item.Amount</td>
                        <td class="align-middle">@item.Movie.Name</td>
                        <td class="align-middle">@item.Movie.Price.ToString("c")</td>
                        <td class="align-middle">@((item.Amount *item.Movie.Price).ToString("c")) </td>
                        <td class="align-middle">
                            <a class="text-damger" asp-controller="Orders" asp-action="RemoveItemFromShoppingCart"
                               asp-route-id="@item.Movie.Id">
                                <i style="color:darkred;" class="bi bi-cart-dash"></i>
                            </a>
                            |
                            <a class="text-success" asp-controller="Orders" asp-action="AddItemToShoppingCart"
                               asp-route-id="@item.Movie.Id">
                                <i style="color:black" class="bi bi-cart-plus"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2"></td>
                    <td><b>Total:</b></td>
                    <td>
                        @Model.ShoppingCartTotal.ToString("c")
                    </td>
                </tr>
            </tfoot>
        </table>
       
        <div class="text-center">
            <div class="btn-group">
                <a class=" btn  darkred  float-right" style="background-color:darkred;color:white" asp-action="CompleteOrder">
                    Complete order
                </a>


                <a class="btn " style="background-color:white;color:darkred;border:2px double darkred" asp-controller="Movies" asp-action="Index">
                    Add more items
                </a>
            </div>
            <br />
            <div style="margin-top:30px" id="paypal-btn"></div>
            <span style="padding:5px"></span>
        </div>
    </div>

</div>

@section Scripts{

    <script src="https://www.paypalobjects.com/api/checkout.js"></script>

    <script>
        let _total = @Html.Raw(Model.ShoppingCartTotal);
        paypal.Button.render({
            //Configure environment
            env: 'sandbox',
            client: {
                sandbox: 'AcKRtgL4i68EZ2ZYuYUx3ilihAg2YhL5dtF_m19A8MjBWVOn6ewNS4M_uV8gA3xi98zTcUq38gUHbVFx'
            },
            //Customize button
            locale: 'en_US',
            style: {
                size: 'small',
                color: 'gold',
                shape: 'pill'
            },
            commit: true,
            //Set up a payment
            payment: function (data, actions) {
                return actions.payment.create({
                    transactions: [{
                        amount: {
                            total: _total,
                            currency: 'USD'
                        }
                    }]
                });
            },
            //Execute the payment
            onAuthorize: function (data, actions) {
                return actions.payment.execute().then(function () {
                    var url = '@Url.Action("CompleteOrder", "Orders", new { })';
                    window.location.href = url;
                });
            }
        }, '#paypal-btn')
    </script>
}